### PR TITLE
Fixed almost all tests on Windows

### PR DESCRIPTION
**Pull request by kukulich**
Before:
```
Tests: 1670, Assertions: 29564, Errors: 1, Failures: 22, Skipped: 6.
```

Now:
```
Tests: 1673, Assertions: 29567, Errors: 1, Skipped: 7.
```

### CODE REVIEW

**Comment by Ocramius** [comment]
Thanks @kukulich!

**Comment by kukulich** [comment]
@Ocramius Thank you very much. It would be much easier to test my pull requests :) I was not able to fix the last test but better than nothing :)

**Comment by Ocramius** [comment]
@kukulich we may add appveyor testing to make sure that windows is also covered

**Comment by Ocramius** [comment]
@kukulich as per https://github.com/Roave/BetterReflection/pull/306, we now have windows-based testing. All tests pass though, so please check your local environment for differences.

**Comment by kukulich** [comment]
@Ocramius The test may be skipped:

My computer:
```
Tests: 1673, Assertions: 29567, Errors: 1, Skipped: 7.
```

AppVeyor:
```
Tests: 1572, Assertions: 22285, Skipped: 29.
```

Travis:
```
Tests: 1654, Assertions: 29927, Skipped: 2.
```

**Comment by Ocramius** [comment]
@kukulich I didn't fine-tune appveyor, but if there's stuff missing there, we should reduce those skipped tests to move towards your environment.

**Comment by kukulich** [comment]
Will try to find the differences and prepare PR for appveyor.yml change.

**Pull request merged**
