### PR TITLE
Fix typo in phpdoc of method that should be `@internal`

### PR DESCRIPTION
**Pull request by shyim**
I am annoyed that my phpstorm autocompletes always `@interal` instead of `@internal`

### CODE REVIEW

**Review by Ocramius — APPROVED** [review]
Thanks @shyim!

**Comment by shyim** [comment]
```
[BC] REMOVED: Method Roave\BetterReflection\Reflection\ReflectionAttribute#withOwner() was removed
[BC] CHANGED: Roave\BetterReflection\Reflection\ReflectionAttribute#withOwner() was marked "@internal"
```

No idea what to do with that 😅

**Comment by Ocramius** [comment]
That one is correct, but can be ignored.

`roave/backward-compatibility-check` is complaining that a method got "removed", because it is now `@internal`, and the tool is technically correct, but nothing we can do about the red build, for now :)

**Comment by mitelg** [comment]
that was the reason why PhpStorm does that? 😅
thanks @shyim I was also annoyed by that the last days 😁

**Pull request merged**
