### PR TITLE
Usage: fix DirectoriesSourceLocator usage

### PR DESCRIPTION
**Pull request by TomasVotruba**
My first usage of this package in years. Let me know if there is another way

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thank you!

Btw, does this work only on class reflections? 

I need also functions and constants, but there is no such method in `FunctionReflector`.

**Comment by Ocramius** [comment]
@TomasVotruba source locators work with any kind of AST node, but we didn't implement constant lookup (only functions and classes, so far)

**Comment by TomasVotruba** [comment]
@Ocramius I see, thanks.

[I didn't find in docs](https://github.com/Roave/BetterReflection/blob/master/docs/usage.md#reflecting-functions), how to get functions from specific directory.


Sth like:

```php
$reflector->getAllFunctions();
```

Is there a way?

**Comment by asgrim** [comment]
@TomasVotruba yes - it was recently added in #252 but it's not been tagged yet :)

**Comment by TomasVotruba** [comment]
@asgrim Perfect, thank you! I can roll on dev for a while :)

**Pull request merged**
