### PR TITLE
Fixed `ReflectionClass::isInstance()` adapter compatibility with native reflection

### PR DESCRIPTION
**Pull request by kukulich**
https://3v4l.org/J1jl9

### CODE REVIEW

**Comment by kukulich** [comment]
Reported as PHP bug: https://bugs.php.net/bug.php?id=79645

**Comment by Ocramius** [comment]
This throws a `TypeError` in PHP 8: shouldn't we align to that behaviour, maybe? Seems more sensible to me...

**Comment by kukulich** [comment]
> This throws a `TypeError` in PHP 8: shouldn't we align to that behaviour, maybe? Seems more sensible to me...

I would change it in version 4.4.0 that will require PHP 7.4.1. It would be easier: https://github.com/Roave/BetterReflection/pull/608/commits/bcd55b2ba9bd3451fba0f1b499e7ce0856910fab#diff-90219491fdbdad675bcb14b0405dc888R385

**Comment by kukulich** [comment]
And probably there are more methods that should `TypeError` then.

**Comment by Ocramius** [comment]
Let's hold off with PHP 8 compatibility then: it will come anyway 👍

**Comment by Ocramius** [comment]
Thanks @kukulich!

**Pull request merged**
