### PR TITLE
Updated CS

### PR DESCRIPTION
**Pull request by kukulich**

### CODE REVIEW

**Comment by kukulich** [comment]
Broken build is unrelated - will try to fix in different PR.

**Comment by asgrim** [comment]
Can rebase this for a green build probably now :)

**Comment by kukulich** [comment]
In the pub after three months 😀 we do later/tomorrow

**Comment by asgrim** [comment]
Cheers! :beers: :laughing:

**Comment by kukulich** [comment]
Rebased.

**Comment by Ocramius** [comment]
CI went through: 🚢

**Pull request merged**
