### PR TITLE
No more Psalm baseline

### PR DESCRIPTION
**Pull request by kukulich**

### CODE REVIEW

**Comment by kukulich** [comment]
I really don't understand it:

```
-3400 mutations were generated:
-    2996 mutants were killed
+3405 mutations were generated:
+    2960 mutants were killed
       11 mutants were not covered by tests
-     147 covered mutants were not detected
+     188 covered mutants were not detected
        8 errors were encountered
        3 syntax errors were encountered
        5 time outs were encountered
      230 mutants required more time than configured
```

**Comment by Ocramius** [comment]
It is likely a bug in `roave/infection-static-analysis-plugin`, which perhaps suppressed much more  than necessary due to the baseline 🤔

**Comment by kukulich** [comment]
It looks it ignored classes from baseline completelly - but not all, eg. `PhpStormStubsSourceStubber` was not ignored 🤷‍♂️

**Review by Ocramius — APPROVED** [review]
LGTM! No baseline is quite a big achievement, even if it lowers MSI :)

**Pull request merged**
