### PR TITLE
CI: use pcov for type coverage

### PR DESCRIPTION
**Pull request by staabm**
just a test whether this speedsup the CI pipeline

### CODE REVIEW

**Comment by Ocramius** [comment]
The biggest offender when it comes to performance here is `roave/infection-static-analysis-plugin` operating (under the hood) with Psalm's analysis, which needs more tuning around file consistency checks, perhaps. 

It's still faster than running all the mutants, but it's also still very slow when considering analysis on a limited set of changed files.

**Comment by staabm** [comment]
I need to dive into `roave/infection-static-analysis-plugin` to understand more what it is actually doing :-).

my naiv thinking of this PR was/is: xdebug makes everything super slow. maybe pcov does have less function call overhead etc and might speedup it. lets see.

**Comment by Ocramius** [comment]
It's really tiny. For each escaped mutant process (generated mutation), it will run static analysis:

https://github.com/Roave/infection-static-analysis-plugin/blob/063ab39377a515ec115d6480367d41d0f1a894a7/src/Roave/InfectionStaticAnalysis/RunStaticAnalysisAgainstEscapedMutant.php#L36-L71

In there, the major-major performance bottleneck is:

```php
if ($this->runStaticAnalysis->isMutantStillValidAccordingToStaticAnalysis($mutantProcess->getMutant())) {
```

**Comment by staabm** [comment]
do you think we could use `--filter` and run several jobs in parallel ?

https://infection.github.io/guide/command-line-options.html

**Comment by Ocramius** [comment]
Possibly, but CI is not as frequent here, so 15m are not worth wasting time on, unless you are looking for very specific mutants.

**Pull request closed without merging**
