### PR TITLE
Improved mutation score

### PR DESCRIPTION
**Pull request by kukulich**

### CODE REVIEW

**Comment by kukulich** [comment]
@Ocramius Btw do we need `ClassLoader` ? It looks it used only in its own tests...

**Comment by Ocramius** [comment]
> It looks it used only in its own tests...

I think it was used in the monkey-patching functionality, but no longer needed: perhaps deprecation + removal in `6.0.0`?

**Review by Ocramius — APPROVED** [review]
LGTM, nice refactoring + code removal 💪

**Comment by Ocramius** [comment]
BTW: 

```
Metrics:
         Mutation Score Indicator (MSI): 97%
         Mutation Code Coverage: 99%
         Covered Code MSI: 97%
```

Perhaps time to raise that threshold again?

**Comment by kukulich** [comment]
> Perhaps time to raise that threshold again?

When I'm done ;)

**Pull request merged**
