### PR TITLE
Bump vimeo/psalm from 5.1.0 to 5.6.0

### PR DESCRIPTION
**Pull request by kukulich**
It's not perfect but it should enable other dependencies upgrades.

### CODE REVIEW

**Comment by kukulich** [comment]
Hmm, I don't know how to fix Psalm on PHP 8.1 :(

**Comment by Ocramius** [comment]
@kukulich sorry, as you may have noticed, I'm not very active this month (due to relocation).

I'll try helping out soon-ish 👍

**Comment by Ocramius** [comment]
If I see it correctly, it's only `getModifiers` that fails, right? 


That's because of `ReflectionClass::IS_*` added constants in PHP 8.2?

**Comment by kukulich** [comment]
Yes, the problem is that we added `IS_READONLY` constant to `ReflectionClass` adapter: https://github.com/Roave/BetterReflection/blob/6.6.x/src/Reflection/Adapter/ReflectionClass.php#L36

And the adapter is now not compatible with native ReflectionClass (and stubs in Psalm) in PHP 8.1.

**Comment by Ocramius** [comment]
I'd say that we bump to 8.2 then :fire: 

While it may be possible to declare an exclusion, it's really not worth making our life harder than it should, and we should encourage upgrading anyway.

**Comment by kukulich** [comment]
We can also just don't run Psalm on PHP 8.1 :)

**Comment by Ocramius** [comment]
Works for me :+1: 

That is excluded via https://github.com/laminas/laminas-ci-matrix-action/tree/c620b3cea1167f97c21b5fa127b1c622863bf4cb#configuration

See https://github.com/laminas/laminas-ci-matrix-action/tree/c620b3cea1167f97c21b5fa127b1c622863bf4cb#excluding-specific-jobs

**Comment by kukulich** [comment]
Still no laminas here so: https://github.com/Roave/BetterReflection/pull/1322/commits/3a0a6816cb515ebffa455494b5a375ae4ca64389

**Comment by Ocramius** [comment]
Was totally convinced that I had adjusted that, sorry :D

**Comment by kukulich** [comment]
The one failed check is expected.

**Comment by Ocramius** [comment]
Indeed, and being an adapter, it is also not a BC break.

Thanks @kukulich!

**Pull request merged**
