### PR TITLE
FIX: ReflectionClass::getImmediateInterfaces fails on anonymous classes

### LINKED ISSUE #664: `ReflectionClass::getImmediateInterfaces` fails on anonymous classes
Given I have following code snippet I want to be analyzed:

```php
<?php

use Roave\BetterReflection\BetterReflection;
use Roave\BetterReflection\Reflector\ClassReflector;
use Roave\BetterReflection\SourceLocator\Type\StringSourceLocator;

require_once __DIR__.'/vendor/autoload.php';

$code = <<<PHP
<?php

declare(strict_types=1);

namespace Tests\SensioLabs\Deptrac\AstRunner\Resolver\Fixtures;

interface InterfaceB
{
}

class ClassA
{
    public function foo()
    {
        return new class() implements InterfaceB {
        };
    }
}

PHP;


$reflector = new ClassReflector(new StringSourceLocator($code, (new BetterReflection())->astLocator()));
$reflectionClasses = $reflector->getAllClasses();

print_r(
    array_keys(
        $reflectionClasses[2]->getImmediateInterfaces()
    )
);
```

I would expect `Tests\SensioLabs\Deptrac\AstRunner\Resolver\Fixtures\InterfaceB` will returned.
But got following exception:
<details>
<pre>
PHP Fatal error:  Uncaught Roave\BetterReflection\Reflector\Exception\IdentifierNotFound: Roave\BetterReflection\Reflection\ReflectionClass "Tests\SensioLabs\Deptrac\AstRunner\Resolver\Fixtures\InterfaceB" could not be found in the located source in ***/deptrac/vendor/roave/better-reflection/src/Reflector/Exception/IdentifierNotFound.php:29
Stack trace:
#0 ***/deptrac/vendor/roave/better-reflection/src/Reflector/ClassReflector.php(39): Roave\BetterReflection\Reflector\Exception\IdentifierNotFound::fromIdentifier(Object(Roave\BetterReflection\Identifier\Identifier))
#1 ***/deptrac/vendor/roave/better-reflection/src/Reflection/ReflectionClass.php(972): Roave\BetterReflection\Reflector\ClassReflector->reflect('Tests\\SensioLab...')
#2 ***/deptrac/vendor/roave/better-reflection/src/Reflection/ReflectionClass.php(1150): Roave\BetterReflection\Reflection\ReflectionClass->reflectClassForNamedNode(Object(PhpP in ***/deptrac/vendor/roave/better-reflection/src/Reflector/Exception/IdentifierNotFound.php on line 29

Fatal error: Uncaught Roave\BetterReflection\Reflector\Exception\IdentifierNotFound: Roave\BetterReflection\Reflection\ReflectionClass "Tests\SensioLabs\Deptrac\AstRunner\Resolver\Fixtures\InterfaceB" could not be found in the located source in ***/deptrac/vendor/roave/better-reflection/src/Reflector/Exception/IdentifierNotFound.php on line 29

Roave\BetterReflection\Reflector\Exception\IdentifierNotFound: Roave\BetterReflection\Reflection\ReflectionClass "Tests\SensioLabs\Deptrac\AstRunner\Resolver\Fixtures\InterfaceB" could not be found in the located source in ***/deptrac/vendor/roave/better-reflection/src/Reflector/Exception/IdentifierNotFound.php on line 29
</pre>
</details>

### PR DESCRIPTION
**Pull request by smoench**
~I'm too lazy to checkout the repository and run the tests. So GitHub actions should do the work~

resolves #664

### CODE REVIEW

**Comment by Ocramius** [comment]
@smoench you know exactly what kind of comment is coming for you ;-)

**Comment by smoench** [comment]
This is an draft you should not have been informed :P

**Comment by smoench** [comment]
@Ocramius There you go. I added a test and pulled the changes of #505. Works so far

**Comment by Ocramius** [comment]
Ooof, this totally went under my radar. 

@asgrim this looks good to me (besides merge conflict) - can you review as well?

**Review by asgrim — APPROVED** [review]

**Comment by smoench** [comment]
I pulled the changes of #505, so that PR should be approved first shouldn't it?

**Comment by asgrim** [comment]
Note: changed base to `4.10.x` branch, since `master` will be removed

**Comment by kukulich** [comment]
This should be fixed in https://github.com/Roave/BetterReflection/pull/750 with https://github.com/kukulich/BetterReflection/commit/569ea7dcb8664ebe031833dbefed03d04ba10a2f

**Pull request closed without merging**
