### PR TITLE
Delete composer.lock

### PR DESCRIPTION
**Pull request by asgrim**
Yep, it's true!

### CODE REVIEW

**Comment by Ocramius** [comment]
@asgrim `composer.lock` should be in `.gitignore`, as this is a library :|

**Comment by asgrim** [comment]
@ocramius updated

**Comment by Ocramius** [comment]
E_NOT_GITIGNORED

**Comment by asgrim** [comment]
@Ocramius fixed

**Comment by Ocramius** [comment]
WHY AM I NOT SLEEPING?!

**Comment by asgrim** [comment]
Thanks, go to sleep

**Pull request merged**
