### PR TITLE
Removed wrong classes and functions from PHPStorm stubs map

### PR DESCRIPTION
**Pull request by kukulich**

### CODE REVIEW

**Comment by theofidry** [comment]
Will need to port that to https://github.com/JetBrains/phpstorm-stubs/pull/614

**Comment by asgrim** [comment]
@theofidry do we want to block this until upstream is merged?

**Comment by theofidry** [comment]
No it's alright, I've referenced it in the PR :)

**Comment by asgrim** [comment]
Alrighty, thanks!

**Comment by asgrim** [comment]
Thanks @kukulich !

**Comment by Ocramius** [comment]
Note: this is still targeting `4.0.0`. Do you need a fix in the current stable release, @kukulich?

**Comment by kukulich** [comment]
It could be in 3.5.1 but it's probably not important. I don't think somebody would use class name `___PHPSTORM_HELPERS\\PS_UNRESERVE_PREFIX_static` :)

**Pull request merged**
