### PR TITLE
Create Foo.php

### PR DESCRIPTION
**Pull request by WinterSilence**

### CODE REVIEW

**Comment by Ocramius** [comment]
@WinterSilence this is wasting huge amounts of CI runs, and leads to a lot of notifications. Please:

 * clone the repository locally
 * work on a patch locally, run tests, static analysis and code style checks there first

Overall, pushing microscopic changes (with bad commit messages) is terrible GitHub etiquette.

**Comment by WinterSilence** [comment]
@Ocramius disable CI for **draft** request. focus on bug fixing

**Comment by Ocramius** [comment]
@WinterSilence sorry, but no: please do write detailed patches, with good/self-explanatory commit messages and tests, and then send them upstream.

I still get notifications for all these `"Update Foo.php"` and `"Update Bar.php"`, so regardless of CI, it's a lot of background notice to be avoided (hence my mention of etiquette).

**Comment by WinterSilence** [comment]
@Ocramius i'm in train and come back only after new year.  i'm don't planed fix it now, only report about problem, but you close issue.  now you close PR written for your. it's not "friendly" and does not help to solve problems

**Pull request closed without merging**
