### PR TITLE
Fixed composer.json

### PR DESCRIPTION
**Pull request by GrahamCampbell**
`@dev` does absolutely nothing because of your prefer-stable directive, and `dev-master` should be avoided at all costs.

### CODE REVIEW

**Comment by asgrim** [comment]
We're fine with `dev-master` for now thanks, we are not stable yet ;)

**Comment by GrahamCampbell** [comment]
It's not about being stable. It's about dev-master being the same as an unbounded dependency, and my vesion constraints load exactly the same version of the code you want.

**Comment by asgrim** [comment]
Yes, I am fully aware of that.

**Comment by Ocramius** [comment]
@GrahamCampbell we simply will have to tell users (for now) to use a `"minimum-stability": "dev"` until we reach stability at all.

**Pull request closed without merging**
