### PR TITLE
Use repeatable cache key from `spl_object_id()` instead of `spl_object_hash()` to reduce memory overhead

### PR DESCRIPTION
**Pull request by mvorisek**
see https://3v4l.org/b4Z1G

also more performant, ref https://github.com/php/php-src/blob/php-8.0.6/ext/spl/php_spl.c#L669

### CODE REVIEW

**Comment by Ocramius** [comment]
Overall only mergeable when/if CI runs with PHP 8.x.

**Comment by mvorisek** [comment]
this can be merged immediatelly into 4.12.x, there was a condition for PHP 7.1 (which is still supported by phpstan), but as 4.12.x already does not support PHP 7.1, no condition is needed (as has nothing to do with PHP 8.0)

**Comment by Ocramius** [comment]
Ah, just saw that you removed the conditional :+1:

**Review by Ocramius — APPROVED** [review]
Thanks @mvorisek!

**Pull request merged**
