### PR TITLE
Update our code for API changes in PHP-Parser

### PR DESCRIPTION
**Pull request by asgrim**
Two things blocking the merge currently:
- [x] Need [`nikic/php-parser`](https://packagist.org/packages/nikic/php-parser) to be released (requires `3.0.0`)
- [x] Need [`jeremeamia/superclosure`](https://packagist.org/packages/jeremeamia/SuperClosure) to do a release (I expect it will be `2.3.0`) - `dev-master` has support for php-parser `3.x` now
- [x] Fix blocking issues/failing tests etc.

### CODE REVIEW

**Comment by asgrim** [comment]
BTW this allows us to unblock and work on #202 and #204

**Comment by asgrim** [comment]
PHP Parser 3.0.0 is now released, still waiting for superclosure to release supporting PHP Parser 3.0.0 I think

**Comment by asgrim** [comment]
For now, going to leave SuperClosure as is here for now and eliminate this external dep in #228

**Comment by asgrim** [comment]
@Ocramius rebased onto `master` following #227 merge

**Comment by Ocramius** [comment]
👍

**Pull request merged**
