### PR TITLE
CS fix

### PR DESCRIPTION
**Pull request by kukulich**
This should fix broken CS in Travis thanks to https://github.com/slevomat/coding-standard/releases/tag/6.0.7

### CODE REVIEW

**Comment by Ocramius** [comment]
Let's please bump in `conposer.json` too

**Comment by kukulich** [comment]
slevomat/coding-standard is not in composer.json, it's installed via doctrine/coding-standard

**Comment by Ocramius** [comment]
Then let's add a `conflict` clause with `<` 6.0.7

**Comment by kukulich** [comment]
Done.

**Pull request merged**
