### PR TITLE
AppVeyor is dead, long live Travis

### PR DESCRIPTION
**Pull request by kukulich**

### CODE REVIEW

**Comment by Ocramius** [comment]
Interesting: build failing (probably) because GIT is checking out everything with the wrong CRLF flags

**Comment by kukulich** [comment]
@Ocramius It should be fixed by https://github.com/Roave/BetterReflection/pull/464/commits/5b56d96be018ed6873159163dde0c3b64635f4a5#diff-fc723d30b02a4cca7a534518111c1a66R1

It works in my other repository. However it looks it does not work in PR :( The `.gitattributes` change has to be in master first probably.

**Comment by Ocramius** [comment]
Ok, let's try this then. If needed, I'll revert.

**Comment by Ocramius** [comment]
Looking good in `master` 👍

**Pull request merged**
