### PR TITLE
Update dependency phpunit/phpunit to v10

### PR DESCRIPTION
**Pull request by kukulich**

### CODE REVIEW

**Comment by kukulich** [comment]
Hmm, on my Windows localhost the mutation tests are ok...

**Comment by Ocramius** [comment]
Looks like a timeout + crash enforced by GitHub actions 🤔

Perhaps slow coverage and no output for too long?

**Comment by kukulich** [comment]
I've enabled debug for the action and re-run it and no error 🤷‍♂️

**Review by Ocramius — APPROVED** [review]
Awesome, thanks @kukulich!

As for the hiccup, it may have been a stuck worker.

**Pull request merged**
