### PR TITLE
various improvements for psalm

### PR DESCRIPTION
**Pull request by orklah**
I fixed some errors, updated baseline.

It improved type coverage a bit.

### CODE REVIEW

**Comment by orklah** [comment]
oh. I missed the fact that node could be null in ReflectionFunctionAbstract because it can be unitialized.

I'll fix that

**Comment by orklah** [comment]
Mmh... when trying to add null to the list of types for node, Psalm highlight 18 other lines where it's not handled.

I could fix that for Psalm by adding assert($this->node !== null); on each method using it, but I'm not sure it's the best way to go... Any thoughts?

**Comment by asgrim** [comment]
@orklah perhaps a private method that asserts the node is set, and update $this->node references to point to that method?

**Comment by orklah** [comment]
> 
> 
> Nice! Looks good, waiting for build 👍

Please wait. I'm trying to reconcile getNode and getInitializedNode, they both do the same thing. I'm just running tests locally

**Comment by orklah** [comment]
It's done, it should pass CI.

Thanks for the advice!

**Comment by orklah** [comment]
fixed some CS issues and rebased

**Pull request merged**
