### PR TITLE
Bump PHPStan to 0.12.9

### PR DESCRIPTION
**Pull request by ondrejmirtes**
BTW do you know that Travis build is set up so that it ignores all failures on PHP 7.4? So if PHPStan or Psalm fail, the build still passes...

### CODE REVIEW

**Comment by Ocramius** [comment]
> BTW do you know that Travis build is set up so that it ignores all failures on PHP 7.4?

Haven't noticed before, urgh :S

**Comment by Ocramius** [comment]
Hmm, fails indeed: can we drop the `.travis.yml` exclusion to make this visible?

**Comment by ondrejmirtes** [comment]
I removed the allowed_failures and ran PHPCBF. Some CS failures still remain...

**Comment by Ocramius** [comment]
@ondrejmirtes I think the remaining issues are fixed in `master`: can you try a rebase here?

**Comment by Ocramius** [comment]
I think @orklah bumped to `0.12.11` already in #548: closing here. Thanks everyone! :tada:

**Pull request closed without merging**
