### PR TITLE
Try to fix the "Auto-merge Dependabot PRs" workflow again

### PR DESCRIPTION
**Pull request by kukulich**

### CODE REVIEW

**Comment by Ocramius** [comment]
Folks, we're trying to attack this from too many angles, IMO.

Simpler approach (which works for my other repos):

 * **one** `continuous-integration.yml` file with all checks in it: https://github.com/Ocramius/LazyMap/blob/e917729673ee605bd09515e66f096b0be1366cd7/.github/workflows/continuous-integration.yml#L4
 * auto-merge workflow relies on that: https://github.com/Ocramius/LazyMap/blob/e917729673ee605bd09515e66f096b0be1366cd7/.github/workflows/merge-dependabot-upgrades.yml#L4-L11

That is a much simpler approach, but requires unifying the various `.yml` files.

For example, `Ocramius/PackageVersions` and `Ocramius/ProxyManager` don't have that, and dependabot PRs don't get merged (and now I fully understand why)

**Comment by kukulich** [comment]
I'm ok to merge it to one file but I was not sure if the author of the split will be happy 😄 

https://github.com/Roave/BetterReflection/commit/555951ff465f5e96f80d5823b3fc9c70b46b053a

**Comment by Ocramius** [comment]
Oh yeah, whatever makes the wheel spin: I totally hate the size of github's unmaintainable `.yml` files, but we worked a lot on stuff like https://github.com/laminas/laminas-ci-matrix-action to simplify some of this mess (to some degree)

EDIT: note that the `laminas/` actions are unlikely applicable to this repo, for now

**Comment by kukulich** [comment]
Ok, will merge the files to `continuous-integration.yml`

**Comment by DanielBadura** [comment]
Dont we just need to list all the names of the yaml files in this list? Like:
```yaml
name: Auto-merge Dependabot PRs

on:
  workflow_run:
    types:
      - completed
    workflows:
      - "Benchmarks"
      - "Check Coding Standards"
```
And so on? Maybe it's worth a try before squashing all yml's?

**Comment by Ocramius** [comment]
Wouldn't that trigger the auto-merge when **any** of those is completed?

**Comment by DanielBadura** [comment]
Thought it first to but i re-read it:
    
> workflows:
>       # List all required workflow names here.
>       - 'Continuous Integration'

This sounds more like all need to be successful, but it's again just try and error.

**Comment by kukulich** [comment]
I hope it's ok 🤷‍♂️

**Review by Ocramius — APPROVED** [review]
Excellent, thanks @kukulich!

**Comment by Ocramius** [comment]
@kukulich @DanielBadura it worked, thank you so much for putting time in this!

https://github.com/Roave/BetterReflection/pull/872

**Pull request merged**
