### PR TITLE
Reproduce #574

### PR DESCRIPTION
**Pull request by ondrejmirtes**
Reproduces #574.

So, this one was a bit tougher. Without the try-catch and die, it completely breaks PHPUnit because of its error handler I suppose. At least this way, I'm able to get the message I'm experiencing in practice: `Class 'App\B' not found`

What's happening is that:

1) I ask BR for class `App\A`.
2) Clas `App\A` in the PHAR extends something outside of the PHAR.
3) Because `file` stream wrapper is overriden, the call fails and we end up with this message.

The solution to this is to also override `phar://` protocol and not just `file://`. It might be a good idea to make the list of protocols configurable through constructor because I guess this can happen with other protocols if people use them to autoload classes...

What's interesting is that unlike #575 and even if there's `@runInSeparateProcess`, this test runs even when I run the full test suite.

### CODE REVIEW

**Comment by Ocramius** [comment]
I'm not sure that (if phars are involved), the `AutoloadSourceLocator` is usable at all: kinda impressed that it still manages to find stuff in phars :O

**Comment by ondrejmirtes** [comment]
With this commit it works :) https://github.com/ondrejmirtes/BetterReflection/commit/e909d2a273e23c96847cbeeb2c1da8846d71a946

As I switched `PHPStan\\` namespace to the static reflection engine yesterday, I was experiencing these failures: https://github.com/phpstan/phpstan/runs/664051706?check_suite_focus=true (because a test case extended RuleTestCase inside `phpstan.phar` which extends PHPUnit's TestCase outside the PHAR). So I know that the fix works.

**Comment by ondrejmirtes** [comment]
If an autoloaded class from inside the PHAR doesn't extend something from outside the PHAR, it works but those classes are actually loaded (because phar:// isn't overriden).

**Comment by asgrim** [comment]
Fix in https://github.com/ondrejmirtes/BetterReflection/commit/e909d2a273e23c96847cbeeb2c1da8846d71a946 seems reasonable! :+1: would that make these added tests pass @ondrejmirtes ?

**Comment by ondrejmirtes** [comment]
Yes, although the code might be nicer with foreaches over an array of protocols :)

**Comment by asgrim** [comment]
Closing this in favour of #582 as your tests have been incorporated there already - thanks @ondrejmirtes !

**Pull request closed without merging**
