### PR TITLE
Automatically add `null` to native union parameter type with `= null` default value

### PR DESCRIPTION
**Pull request by ondrejmirtes**

### CODE REVIEW

**Review by Ocramius — APPROVED** [review]

**Comment by Ocramius** [comment]
Potentially to be cherry-picked into `5.3.1`

**Review by kukulich — APPROVED** [review]

**Comment by kukulich** [comment]
LGTM.

**Comment by Ocramius** [comment]
I'll cherry-pick onto `5.3.x` and release a patch in a few (sitting in meetings)

**Comment by Ocramius** [comment]
Thanks @ondrejmirtes - cutting a release :+1:

**Comment by ondrejmirtes** [comment]
Thank you :)

**Pull request merged**
