### PR TITLE
Fixed error on anonymous classes with interfaces

### PR DESCRIPTION
**Pull request by prisis**
should i send the same fix for v2?

### CODE REVIEW

**Comment by prisis** [comment]
Something is wrong with travis ...

**Comment by asgrim** [comment]
@prisis  #425 that was causing the test failures here has now been merged, please could you rebase this PR to the latest `master`?

**Comment by asgrim** [comment]
No need to patch v2; it's not a security fix so I think we're good, thanks :+1:

**Comment by prisis** [comment]
done and changed the base brach to master

**Comment by Ocramius** [comment]
Thanks @prisis!

**Pull request merged**
