### PR TITLE
[WIP] Update to PHP-Parser v4

### PR DESCRIPTION
**Pull request by carusogabriel**

### CODE REVIEW

**Comment by kukulich** [comment]
@carusogabriel Shit, I'm working on it too :D

**Comment by carusogabriel** [comment]
@kukulich Most of this changes came from https://github.com/rectorphp/BetterReflection, but there're some tests that are still failing. 

Are you working on your fork? Then I can take a look and we can divide the work!

**Comment by kukulich** [comment]
@carusogabriel https://github.com/kukulich/BetterReflection/tree/php-parser4

My tests are ok, currently there's a problem with PHPStan (not supported new PHP-Parser) and CS (bug in my Slevomat CS).

**Comment by carusogabriel** [comment]
@kukulich May I use some of your changes? Gonna you as a [co-author](https://blog.github.com/2018-01-29-commit-together-with-co-authors/), okay? :smile:

**Comment by kukulich** [comment]
@carusogabriel Or maybe I should open new PR, hmm? I'm still cleaning the code. Some code can be removed now.

**Comment by carusogabriel** [comment]
@kukulich Yes, perfect, please open!

**Pull request closed without merging**
