### PR TITLE
Improved AST traversing - all levels are inspected now

### PR DESCRIPTION
**Pull request by kukulich**
Needed for https://github.com/Roave/BetterReflection/pull/300

### CODE REVIEW

**Comment by Ocramius** [comment]
@kukulich do you have an example where the previous approach fails? The fact that this change comes without test additions is worrisome, and a blocker.

**Comment by kukulich** [comment]
@Ocramius As I've mention it's needed for https://github.com/Roave/BetterReflection/pull/300.

There was no bug currently because namespaces had special handling in previous code. So it's improvement not a bug.

I've just added a test for anonymous class.

**Comment by Ocramius** [comment]
@kukulich thanks for adding the test - it demonstrates that the code works as expected, and that's what makes me happy :+1: 

I manually merged after applying nitpicks. Specifically, the by-ref stuff is gone, as well as some if/else cleanup that was long overdue.

**Comment by kukulich** [comment]
@Ocramius Thanks! I especially happy you removed the by-ref stuff. I was very sad I didn't find better solution. It's perfect you find it 👍

**Pull request merged**
