### PR TITLE
Added missing documentation of AnonymousClassObjectSourceLocator

### PR DESCRIPTION
**Pull request by kukulich**

### CODE REVIEW

**Comment by Ocramius** [comment]
@kukulich should we mark that one as `@internal` though? It's not really meant for userland...

**Comment by kukulich** [comment]
@Ocramius Not sure. The `ClosureSourceLocator` is also not marked as internal.

**Comment by Ocramius** [comment]
@kukulich I suggest at least marking it as such

**Comment by kukulich** [comment]
@Ocramius Added second commit.

**Comment by Ocramius** [comment]
:ship:

**Comment by Ocramius** [comment]
Thanks @kukulich!

**Pull request merged**
