### PR TITLE
Added allow-plugins for composer 2.2

### PR DESCRIPTION
**Pull request by sasezaki**
https://blog.packagist.com/composer-2-2/

### CODE REVIEW

**Comment by kukulich** [comment]
@sasezaki see https://github.com/Roave/BetterReflection/pull/920

**Comment by Ocramius** [comment]
Closing as per @kukulich's comment.

Indeed, we don't want to clutter anything more than necessary here, especially if it transitively got in via `composer.lock`.

**Comment by sasezaki** [comment]
I'm sorry, did not notice #920.

**Comment by Ocramius** [comment]
@sasezaki no worries, it's not expected of contributors to dig through our history :)

**Pull request closed without merging**
