### PR TITLE
Improved mutation score

### PR DESCRIPTION
**Pull request by kukulich**

### CODE REVIEW

**Review by Ocramius — APPROVED** [review]
LGTM 👍

**Review by Ocramius — APPROVED** [review]

**Comment by Ocramius** [comment]
🚢  thanks @kukulich!

**Comment by kukulich** [comment]
@Ocramius 

Btw I really don't understand a lot of mutants in `PhpStormStubsSourceStubber`, eg.

```
218) /home/runner/work/BetterReflection/BetterReflection/src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php:701    [M] IncrementInteger

--- Original
+++ New
@@ @@
     private function parsePhpVersion(string $version) : int
     {
         $parts = array_map('intval', explode('.', $version));
-        return $parts[0] * 10000 + $parts[1] * 100 + ($parts[2] ?? 0);
+        return $parts[0] * 10000 + $parts[2] * 100 + ($parts[2] ?? 0);
```

There are tests that fail when I apply this change.

**Comment by Ocramius** [comment]
> There are tests that fail when I apply this change.

Sounds like a coverage / affected tests bug in `infection/*` :thinking:

**Pull request merged**
