### PR TITLE
Basic support for PHP 8.2

### PR DESCRIPTION
**Pull request by kukulich**

### CODE REVIEW

**Comment by Ocramius** [comment]
I could release this as last 5.x, unless more 8.2 additions can be done without BC issues? 🤔

**Comment by kukulich** [comment]
I think the last 8.2 addidition will be https://wiki.php.net/rfc/constants_in_traits and I'm currently expecting it could be done without BC breaks. I plan to prepare it soon.

**Comment by Ocramius** [comment]
Ok, we should then keep the milestone open until that is through, and then we can merge all BC breaking changes and prepare 6.0.0 💪

**Review by Ocramius — APPROVED** [review]
🚢 thanks @kukulich!

**Pull request merged**
