### PR TITLE
Removed `ReflectionClass::getAst()` to prevent memory leaks

### LINKED ISSUE #1073: Prevent memory leaks by not holding onto AST nodes
Hi, I'm in the process of reducing the memory amount consumed by PHPStan, and I have some promising results.

Current stable version consumes ~850 MB when runing PHPStan on PHPStan.

After I removed the NodeConnectingVisitor (this isn't related to BetterReflection) that creates cycles between nodes by setting parent/previous/next attributes, I saved around 100 MB. So now we're at ~750 MB.

I continued to debug the problem by using [php-meminfo](https://github.com/BitOne/php-meminfo) but there was a lot of noise because of CachedParser (equivalent of MemoizingParser). So I removed parser caching to see what else holds onto AST nodes. I also removed static reflection capabilities altogether to see if there's something else in PHPStan that leaks. I consider the floor of what's possible to achieve at around ~200 MB.

When I returned static reflection capabilities, it went back to ~750 MB. And most of the memory is held in AST nodes held by various reflection classes like ReflectionClass etc.

So I refactored some classes to extract all of the needed information in constructor so that the AST node is not saved in a property: https://github.com/ondrejmirtes/BetterReflection/compare/cc581ecece6e69674181ec456ecc5d846ad312d1...35db84f1abff5b3416daca4804901b0750da7610 (the work isn't done, there's still more to do)

Right now PHPStan consumes around 340 MB without a CachingParser and around 430 MB with a CachingParser.

The best part is that there's very little performance impact time-wise so it looks really promising. I don't have production-ready code yet as there are some problems to work out but I hope this will make PHPStan much more resource-effective.

One downside is that I had to remove some features that need the AST after a Reflection class is created - it can be seen in the diff.

Is this something you'd like to do here too?

### PR DESCRIPTION
**Pull request by kukulich**
Last part of https://github.com/Roave/BetterReflection/issues/1073

Fixes #1073

### CODE REVIEW

**Comment by Ocramius** [comment]
Should we roll 6.0.0 after this?

**Comment by kukulich** [comment]
I think we should give some time to @ondrejmirtes to test it in PHPStan. He may find some problems that will need another BC break.

**Comment by kukulich** [comment]
6.0 will be big release so may I rename `ReflectionClass::getImmediateReflectionConstants()` to `getImmediateConstants()`? To make it compatible with `getImmediateMethods()` etc.

**Comment by Ocramius** [comment]
Works for me, let's just not push the goalpost too far, since "done" is better than perfect, and we're already near damn perfect :D

**Review by Ocramius — APPROVED** [review]
Excellent, thanks!

**Pull request merged**
