### PR TITLE
#430 Add ability to specify doc comment for the functions

### PR DESCRIPTION
**Pull request by funivan**

### CODE REVIEW

**Comment by funivan** [comment]
@asgrim need some help. Tests failed on unexpected place:
```
ERROR: UndefinedPropertyFetch - src/Reflection/ReflectionFunctionAbstract.php:566:29 - Instance property PhpParser\Node\Expr\Error::$name is not defined
            if (! is_string($paramNode->var->name) || strtolower($paramNode->var->name) !== $lowerName) {
ERROR: UndefinedPropertyFetch - src/TypesFinder/FindParameterType.php:56:50 - Instance property PhpParser\Node\Expr\Error::$name is not defined
            if ($paramTag->getVariableName() === $node->var->name) {
```
I think this is not my bug.

**Comment by asgrim** [comment]
@funivan indeed, I'm investigating this in #425 so hopefully we'll get that merged soon :)

**Comment by asgrim** [comment]
@funivan #425 that was causing the test failures here has now been merged, please could you rebase this PR to the latest `master`?

**Comment by funivan** [comment]
done )

**Comment by asgrim** [comment]
@funivan hmm, there seem to be some additional commits added here which shouldn't be part of this change..

To fix, please could you try this (assuming your `upstream` remote is `git@github.com:Roave/BetterReflection.git` or the https version):

 * `git fetch upstream`
 * `git checkout master`
 * `git reset --hard upstream/master`
 * `git checkout 430-change-method-comment`
 * `git rebase -i master`

Remove the additional commits, it should look something like this I think (not exactly):

```
pick abc123a #430 Add ability to specify doc comment for the functions
pick abc123b #430 fix code style
```

 * `git push -f origin 430-change-method-comment`

Please ping me if you need a hand! :)

**Comment by funivan** [comment]
Done.

**Pull request merged**
