### PR TITLE
Move CS, static analysis checks and benchmarks to github actions

### PR DESCRIPTION
**Pull request by Lctrs**
Let's parallelize CI

### CODE REVIEW

**Comment by Ocramius** [comment]
> Actions is not available for legacy per-repository billing plans.

Sorry, we can't enable them on `Roave/` repositories, even the public ones :-(

**Comment by Lctrs** [comment]
:cry:

**Comment by Ocramius** [comment]
Also, updating Roave to use the newer plan would cost a real punch in the stomach O_O

**Comment by Lctrs** [comment]
Can't the gazillions of $ you make by requiring recent PHP versions in your libraries cover this ? :smile: 

More seriously, no problem. I understand.

**Comment by Ocramius** [comment]
I'll have to find a solution anyway, since I'm planning to move to actions as well :|

**Comment by ondrejmirtes** [comment]
FYI at Slevomat we switched to the GitHub Free plan (https://github.com/pricing) and we have GitHub Actions available for the public repositories :)

**Comment by Ocramius** [comment]
Yup, we just switched to the new plan yesterday as well :+1:

**Pull request closed without merging**
