### PR TITLE
Optimized `ReflectionClass::getName()` for anonymous classes

### LINKED ISSUE #1300: Infinite recursion while scanning code containing anonymous classes at multiple inheritance levels
First of all, thanks for great package. It is very helpful for me.

Sometimes your package is trying to analyse classes multiple (infinite) times. I didn't figure out how and why, but I've created minimalistic repository to reproduce issue. The repository is here: https://github.com/lulco/bc-break-demo

Please follow the readme to reproduce. I've added debug output to DefaultReflector and I can see this output:
```
string(21) "BcBreakDemo\Demo\Demo"
string(21) "BcBreakDemo\Demo\Demo"
string(41) "Nette\Forms\Rendering\DefaultFormRenderer"
string(17) "Nette\SmartObject"
string(16) "Nette\Forms\Form"
string(21) "Nette\Forms\Container"
string(30) "Nette\ComponentModel\Container"
string(30) "Nette\ComponentModel\Component"
string(32) "Nette\Forms\Controls\BaseControl"
string(30) "Nette\ComponentModel\Component"
string(29) "PhpParser\NodeVisitorAbstract"
string(16) "Nette\Forms\Form"
string(21) "Nette\Forms\Container"
string(30) "Nette\ComponentModel\Container"
string(30) "Nette\ComponentModel\Component"
string(32) "Nette\Forms\Controls\BaseControl"
string(30) "Nette\ComponentModel\Component"
string(29) "PhpParser\NodeVisitorAbstract"
string(16) "Nette\Forms\Form"
string(21) "Nette\Forms\Container"
string(30) "Nette\ComponentModel\Container"
string(30) "Nette\ComponentModel\Component"
string(32) "Nette\Forms\Controls\BaseControl"
string(30) "Nette\ComponentModel\Component"
string(29) "PhpParser\NodeVisitorAbstract"
string(16) "Nette\Forms\Form"
string(21) "Nette\Forms\Container"
string(30) "Nette\ComponentModel\Container"
string(30) "Nette\ComponentModel\Component"
string(32) "Nette\Forms\Controls\BaseControl"
string(30) "Nette\ComponentModel\Component"
string(29) "PhpParser\NodeVisitorAbstract"
string(16) "Nette\Forms\Form"
string(21) "Nette\Forms\Container"
string(30) "Nette\ComponentModel\Container"
string(30) "Nette\ComponentModel\Component"
string(32) "Nette\Forms\Controls\BaseControl"
string(30) "Nette\ComponentModel\Component"
string(29) "PhpParser\NodeVisitorAbstract"
string(16) "Nette\Forms\Form"
string(21) "Nette\Forms\Container"
string(30) "Nette\ComponentModel\Container"
string(30) "Nette\ComponentModel\Component"
string(32) "Nette\Forms\Controls\BaseControl"
string(30) "Nette\ComponentModel\Component"
string(29) "PhpParser\NodeVisitorAbstract"
string(16) "Nette\Forms\Form"
string(21) "Nette\Forms\Container"
string(30) "Nette\ComponentModel\Container"
string(30) "Nette\ComponentModel\Component"
string(32) "Nette\Forms\Controls\BaseControl"
string(30) "Nette\ComponentModel\Component"
string(29) "PhpParser\NodeVisitorAbstract"
```

Maybe it is somehow connected to this issue https://github.com/Roave/BetterReflection/issues/504

### PR DESCRIPTION
**Pull request by kukulich**
Fixes #1300

### CODE REVIEW

**Comment by Ocramius** [comment]
@kukulich ok, this fixes #1300, but do we have any way to demonstrate that? :thinking:

**Comment by kukulich** [comment]
@Ocramius Just added test that fails (infinite loop) without the optimization.

**Review by Ocramius — APPROVED** [review]
Now this makes a lot more sense, thanks @kukulich! :muscle:

**Comment by Ocramius** [comment]
Thanks @kukulich!

**Pull request merged**
