### PR TITLE
Support for `final` modifier in traits

### PR DESCRIPTION
**Pull request by kukulich**

### CODE REVIEW

**Comment by Ocramius** [comment]
So... It's already supported? 🤔

**Comment by kukulich** [comment]
@Ocramius Thank you :) I've checked it again and find a bug :)

**Comment by kukulich** [comment]
Ok, it looks the test was right because the behaviour is a little strange and it removes visibility modifiers https://3v4l.org/fS33Y#v8.3.0

**Comment by kukulich** [comment]
https://github.com/php/php-src/issues/12854

**Comment by Ocramius** [comment]
This is now in PHP 8.3.2+

https://github.com/php/php-src/commit/e679ab36b362c34b899672c36982b194a5e98ce3

Worth moving forward?

**Comment by kukulich** [comment]
Yes, it's in my todo list :)

**Review by Ocramius — APPROVED** [review]
Thanks @kukulich! One day, traits will make sense in PHP: that's not today

**Pull request merged**
