### PR TITLE
Added FindReflectionOnLine helper utility

### PR DESCRIPTION
**Pull request by asgrim**
Attempt number 2 and solving #178 in a nicer way.

This provides an API as per the documentation written in `docs/find-reflection-on-line.md`.

### CODE REVIEW

**Comment by asgrim** [comment]
ping @sebastianbergmann - have you had a chance to look over this change, and whether it's suitable for your needs, please?

**Comment by sebastianbergmann** [comment]
Not yet, sorry. Hopefully tomorrow.

**Comment by sebastianbergmann** [comment]
I had a chance to look at this and it does what I need. Thanks!

Can you explain, though, why you chose to implement this as a functor (using `__invoke()`) instead of a straight-forward public method?

**Comment by asgrim** [comment]
The class has a single purpose, so no need for any other public API really. Can be used throw-away, for example in PHP 7, something like this should work (didn't check syntax btw):

```php
$reflection = (new FindReflectionOnLine)($file, $line);
```

**Comment by Ocramius** [comment]
This is good to go: merging!

**Pull request merged**
