### PR TITLE
PHP 8.3 build

### PR DESCRIPTION
**Pull request by michael-rubel**
## About

Allows the usage in PHP 8.3.

### CODE REVIEW

**Review by Ocramius — APPROVED** [review]
From my PoV, this is fine. Looking at RFCs in PHP 8.3, we don't have anything left either:

* [Deprecations for PHP 8.3](https://wiki.php.net/rfc/deprecations_php_8_3) (Created 2022-08-01)
* [Path to Saner Increment/Decrement operators](https://wiki.php.net/rfc/saner-inc-dec-operators) (Discussion started: 2023-01-17, Voting start: 2023-06-28, Voting end: 2023-07-12)
* [Marking overridden methods (#[\Override])](https://wiki.php.net/rfc/marking_overriden_methods) (Created: 2023-05-06, Voting started: 2023-06-14)
* [Arbitrary static variable initializers](https://wiki.php.net/rfc/arbitrary_static_variable_initializers) (Created 2022-11-06)
* [Make unserialize() emit a warning for trailing data](https://wiki.php.net/rfc/unserialize_warn_on_trailing_data) (Discussion started: 2023-03-27)
* [Dynamic class constant fetch](https://wiki.php.net/rfc/dynamic_class_constant_fetch) (Created 2022-11-04)
* [Improve unserialize() error handling](https://wiki.php.net/rfc/improve_unserialize_error_handling) (Created 2022-09-01, Voting opened 2022-10-14, Voting closed 2022-10-28)
* [Readonly amendments](https://wiki.php.net/rfc/readonly_amendments) (Created 2022-10-24)
* [Typed Class Constants](https://wiki.php.net/rfc/typed_class_constants) (Discussion started: 2023-01-31, Voting started: 2023-02-27)
* [Deprecate remains of string evaluated code assertions](https://wiki.php.net/rfc/assert-string-eval-cleanup) (Created: 2023-05-31, Voting start: 2023-06-28, Voting end: 2023-07-12)
* [mb_str_pad](https://wiki.php.net/rfc/mb_str_pad) (Created: 2023-05-19, Discussion started: 2023-05-20, Voting started: 2023-06-05, Voting closed: 2023-06-19)
* [Saner array_(sum|product)()](https://wiki.php.net/rfc/saner-array-sum-product) (Discussion started: 2023-01-17, Voting opened 2023-02-20, Voting closed 2023-03-06, Implemented: 2023-03-07)
* [Define proper semantics for range() function](https://wiki.php.net/rfc/proper-range-semantics) (Discussion started: 2023-03-27, Voting started: 2023-06-01, Voting ended: 2023-06-15)
* [Randomizer Additions](https://wiki.php.net/rfc/randomizer_additions) (Created 2022-10-09)
* [More Appropriate Date/Time Exceptions](https://wiki.php.net/rfc/datetime-exceptions) (Created 2022-11-29, Implemented: 2023-02-08)
* [json_validate function](https://wiki.php.net/rfc/json_validate) (Created 2022-08-14, Voting closed: 2022-10-07)
* [Use exceptions by default in SQLite3 extension](https://wiki.php.net/rfc/sqlite3_exceptions)
* [Deprecate functions with overloaded signatures](https://wiki.php.net/rfc/deprecate_functions_with_overloaded_signatures) (Discussion started: 2023-04-27, Voting started: 2023-06-26, Voting ended: 2023-07-10)


We seem to already support typed class constants:

 * https://github.com/Roave/BetterReflection/pull/1374
 * https://github.com/Roave/BetterReflection/pull/1369

Once this is green, IMO :ship:

**Comment by kukulich** [comment]
@ondrejmirtes has pointed me one more 8.3 feature https://github.com/php/php-src/commit/79d024ac0e2a07b93362a5a2fd4ef36f61fca8fb

**Review by kukulich — APPROVED** [review]

**Comment by Ocramius** [comment]
@michael-rubel can you lower the minimum mutation test core to make CI pass?

```
Error: ] The minimum required MSI percentage should be 100%, but actual is      
         99.73%. Improve your tests!  
```

I'm opening a separate issue to improve that again, meanwhile.

**Comment by michael-rubel** [comment]
@Ocramius Done.

**Comment by Ocramius** [comment]
> @ondrejmirtes has pointed me one more 8.3 feature [php/php-src@79d024a](https://github.com/php/php-src/commit/79d024ac0e2a07b93362a5a2fd4ef36f61fca8fb)

giphy

**Review by Ocramius — APPROVED** [review]
Thanks @michael-rubel!

**Pull request merged**
