### PR TITLE
Try to fix auto-merge for dependatbot PR's

### PR DESCRIPTION
**Pull request by DanielBadura**
As far as I understand to docs from the auto-merge action (https://github.com/ridedott/merge-me-action#public-repositories) using the `check_suite` option you need to remove the if part from the action.

### CODE REVIEW

**Review by Ocramius — APPROVED** [review]
Let's try it 🤷‍♀️

**Comment by DanielBadura** [comment]
This whole auto-merge with new dependabot is such a documentation mess 😂

**Comment by Ocramius** [comment]
Agreed, and so is GitHub actions itself.

Perhaps the only way is to "ship it yourself" with a single massive CI workflow.

**Comment by kukulich** [comment]
I think it will not fix it.

The action is not launched at all: https://github.com/Roave/BetterReflection/actions/workflows/merge-dependabot-upgrades.yml

**Comment by DanielBadura** [comment]
Well CI is still running needs some time for infection check

**Pull request merged**
