### PR TITLE
Composer-specific source locator builder

### LINKED ISSUE #442: Add a source locator that can detect `"autoload"` and `"autoload-dev"` when given a composer schema definition from either a `composer.json` or a `composer.lock`
Given a `composer.json`-alike array and a `string $sourcesBasePath`

```php
['autoload' => [
    'psr-0' => [/* ... */],
    'psr-4' => [/* ... */],
    'classmap' => [/* ... */],
    'files' => [/* ... */],
    'exclude-from-classmap' => [/* ... */],
]];
```

we can generate a `SourceLocator` instance that closes around it.

### PR DESCRIPTION
**Pull request by Ocramius**
Fixes #442

TODOs:

 * [x] testing
 * [x] ~~do we want `beberlei/assert`?~~ removed
 * [x] a `composer.json`-**only** loader (no `vendor/` considered)
 * [x] docs

### CODE REVIEW

**Comment by Ocramius** [comment]
Whew, my idea for https://github.com/Roave/BackwardCompatibilityCheck/issues/110 is indeed working here: analysing a whole reflection tree is an order of magnitude faster this way, although we may still speed up things by nod jumping through the source locators.

**Comment by Ocramius** [comment]
Note: still fails when trying to locate `symfony/console` or `doctrine/common` classes, so I might need to inspect this further

**Comment by Ocramius** [comment]
@kukulich this is now ready - if you are working on the repo these days, can you give it a quick skim please?

**Comment by kukulich** [comment]
Looks good to me 👍

**Comment by Ocramius** [comment]
Thanks @kukulich: preparing a release in the next hours 👍

**Pull request merged**
