### PR TITLE
CompileNodeToValueTest: failing tests for unsupported default values (enum case, new)

### PR DESCRIPTION
**Pull request by janedbal**
I was trying to fix this issue, but it looks like it is not designed for non-scalar values: `ReflectionParameter::getDefaultValue(): string|int|float|bool|array|null`.

----------

The actual issue we are facing is that we [initialize custom attribute](https://www.php.net/manual/en/reflectionattribute.newinstance.php) within custom phpstan rule. When a default value of such attribute is enum case, phpstan collapses.

### CODE REVIEW

**Comment by Ocramius** [comment]
This is correct: `getDefaultValue()` cannot produce `object`, as it goes against the basic invariant of `roave/better-reflection` not loading any of the code being analyzed.

**Comment by kukulich** [comment]
@janedbal it can be “fixed” in https://github.com/ondrejmirtes/BetterReflection

**Comment by Ocramius** [comment]
Certainly, but the basic invariant here is "don't load code", so that will certainly not happen here.

Also for the fork, loading runtime code could even be categorized as a security issue, from my point of view: instead of loading the code, load the AST for it instead.

**Comment by JanTvrdik** [comment]
If it cannot be fixed, which I understand, could it at least throw better exception in such cases?

**Comment by Ocramius** [comment]
@JanTvrdik what's the current exception you get? We generally have quite specific exception types.

Is it this one, perhaps? 

https://github.com/Roave/BetterReflection/blob/ce6a9a27c746fbd45d5a6603ba24e7d4a1f3b0f7/src/NodeCompiler/CompileNodeToValue.php#LL132C35-L132C35

Another alternative that comes to mind is having `BetterReflection` operating in "unsafe mode": something like `new Reflector($yesIReallyWantToExposeMyselfToRCEAttacksWhileInspectingForeignCodebases = true)`

**Comment by janedbal** [comment]
Maybe worth updating [Compatibility page](https://github.com/Roave/BetterReflection/blob/6.11.x/docs/compatibility.md) with this issue? [ReflectionAttribute](https://www.php.net/manual/en/class.reflectionattribute.php) is missing there completely.

**Comment by JanTvrdik** [comment]
@Ocramius It's actually https://github.com/Roave/BetterReflection/blob/6.11.x/src/NodeCompiler/CompileNodeToValue.php#L250, because the "enum case fetch" is represented as `ClassConstFetch` in AST. So instead of "constant not found" error I would expect "enum values are unsupported" error.

**Comment by Ocramius** [comment]
@janedbal please do send a patch :-) 

@JanTvrdik is it possible to have a test with a better message expectation, perhaps? That would certainly improve the DX a lot :)

**Pull request closed without merging**
