### PR TITLE
Removed the ability to monkey patch the code

### PR DESCRIPTION
**Pull request by kukulich**

### CODE REVIEW

**Comment by Ocramius** [comment]
@WyriHaximus you may want to have a say on this too - I believe you did some monkey-patching stuff?

Just making sure of it, before we chop it off...

**Comment by WyriHaximus** [comment]
@Ocramius Pull the trigger, already have a PR for that ready with fibers in 8.1 being the way forward: https://github.com/friends-of-reactphp/http-middleware-psr15-adapter/pull/8

**Review by Ocramius — APPROVED** [review]
:ship: :fire:

**Comment by Ocramius** [comment]
Thanks @kukulich

**Pull request merged**
