### PR TITLE
Use composer 2.1 for tests temporarily

### PR DESCRIPTION
**Pull request by kukulich**

### CODE REVIEW

**Comment by kukulich** [comment]
Created on my parents' computer :) It looks it works :)

**Comment by Ocramius** [comment]
Dude, go do xmas stuff :D

**Comment by Ocramius** [comment]
I'll lock to `composer:2.1` for the time being - will first inspect if/where we use `composer` in the test suite though

**Comment by kukulich** [comment]
Ok, I'm not able to amend commits in GitHub codespaces so fun is over :)

Btw the problem is with PHPUnit process isolation (see https://github.com/composer/composer/commit/7d1ca1f56d81e7641e4c5b7716472c582e3841a6) so I've added composer 2.1 to all actions when it can be needed. I expect it's solution only for a couple of days.

**Comment by kukulich** [comment]
Rebased with composer 2.1.

**Review by Ocramius — APPROVED** [review]
:ship: thanks @kukulich!

**Pull request merged**
