### PR TITLE
More PHPT tests

### LINKED ISSUE #12: Add core reflection .phpt tests to ensure compatibility
For compatibility, we could run tests vs the internal reflection to ensure the same results are achieved for maximum awesometowns.

### PR DESCRIPTION
**Pull request by asgrim**
This aims to implement as many PHPT tests as possible to resolve #12

### CODE REVIEW

**Comment by Ocramius** [comment]
@asgrim still `[WIP]`?

**Comment by asgrim** [comment]
@Ocramius yes, there's loads more tests to add....

**Comment by asgrim** [comment]
@Ocramius Right, most of the compat tests are failing, but they're in now. There's numerous issues to go through, I've created just a couple of bugs for now, but this is a huge undertaking... Getting these `.phpt` tests to all be green for a `1.0.0` release is totally unrealistic imo...

**Comment by asgrim** [comment]
(I removed the .phpt test from running on normal test suite, so you must run manually using `vendor/bin/phpunit test/compat` btw)

**Pull request merged**
